version: '2.1'

services:

  customer_db:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:8000"
    env_file:
      - api.env
    depends_on:
      - mongodb
    networks:
      - backbone

  mongodb:
    image: mongo:3.6
    command: mongod
    env_file:
      - mongo.env
    networks:
      - backbone
      
networks: 
  backbone:
    driver: bridge
    
