openapi: 3.0.0
info:
  description: ''
  version: 0.1.0
  title: Customer DB
tags:
  - name: Customer DB
    description: ''
paths:
  /customer/post:
    post:
      tags:
        - customer
      summary: add a new customer to database
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.post_customer
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        description: customer details
        required: true
  /customer/get:
    get:
      tags:
        - customer
      summary: retrieve customer details
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.get_customer
      parameters:
        - in: query
          name: id
          description: customer id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
  /customer/put/{id}:
    put:
      tags:
      - customer
      summary: update customer
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.put_customer
      parameters:
      - name: id
        in: path
        description: customer id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parameter'
        description: name of data field and new value
        required: true

  /invoice/post:
    post:
      tags:
        - invoice
      summary: add new invoice details to database
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.post_invoice
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invoice'
        description: invoice details
        required: true
  /invoice/get:
    get:
      tags:
        - invoice
      summary: retrieve invoice details
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.get_invoice
      parameters:
        - in: query
          name: id
          description: invoice detail id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
  /invoice/put/{id}:
    put:
      tags:
      - invoice
      summary: update invoice details
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.put_invoice
      parameters:
      - name: id
        in: path
        description: customer id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parameter'
        description: name of data field and new value
        required: true

  /payment/post:
    post:
      tags:
        - payment
      summary: add new payment status to database
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.post_payment
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
        description: payment status
        required: true
  /payment/get:
    get:
      tags:
        - payment
      summary: retrieve payment status
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.get_payment
      parameters:
        - in: query
          name: id
          description: payment status id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
  /payment/put/{id}:
    put:
      tags:
      - payment
      summary: update payment status
      description: ''
      operationId: swagger_server.controllers.customer_db_functions.put_payment
      parameters:
      - name: id
        in: path
        description: customer id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Authentication error
        '409':
          description: Conflict
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parameter'
        description: name of data field and new value
        required: true

servers:
  - url: 'http://localhost:8000/v0.1'
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        billing_type:
          type: string
        billing_id:
          type: string
        currency:
          type: string
        contact:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            phone:
              type: object
              properties:
                number: 
                  type: string
                country_code:
                  type: string
      xml:
        name: Customer
    Invoice:
      type: object
      properties:
        customer_id:
          type: string
        address:
          type: object
          properties:
            name:
              type: string
            street:
              type: string
            number:
              type: string
            city:
              type: string
            zip:
              type: string
            state:
              type: string
            country: 
              type: string
        payment:
          type: object
          properties:
            currency: 
              type: string
            frequency:
              type: string
            frequency_interval:
              type: string
      xml:
        name: Invoice
    Payment:
      type: object
      properties:
        customer_id:
          type: string
        query_id:
          type: string
        payment:
          type: object
          properties:
            price:
              type: object
              properties:
                amount:
                  type: string
                currency:
                  type: string
            complete:
              type: string
            timestamp:
              type: string
      xml:
        name: Payment
    Parameter:
      type: object
      properties:
        field:
          type: string
        value:
          type: string
      xml:
        name: Parameter

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
